version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'  # Puerto de MongoDB
    volumes:
      - mongodb_data:/data/db  # Volumen para persistir los datos de MongoDB

  petfind_blog_ms:
    build: .
    container_name: petfind_blog_ms
    ports:
      - '5000:5000'  # Puerto de tu aplicación Node.js
    environment:
      - mongoUrl=mongodb://mongodb:27017/PetFindBlog  # URL de conexión a MongoDB
    depends_on:
      - mongodb  # Dependencia de MongoDB
    links:
      - mongodb:mongodb  # Enlace con el contenedor de MongoDB
    
volumes:
  mongodb_data:
